### PR TITLE
Update to blevesearch v2.0.1

### PR DESCRIPTION
**Pull request by lafriks**
v2.0.0 introduces breaking changes. Needed to upgrade for Gitea

https://github.com/blevesearch/bleve/releases/tag/v2.0.0

### CODE REVIEW

**Review by 6543 — APPROVED** [review]
`go test ./...` PASSED

**Comment by lafriks** [comment]
Would be nice to tag also after merge

**Comment by 6543** [comment]
@ethantkoenig ping ;)

**Comment by ethantkoenig** [comment]
Sorry for the delay... haven't used Golang in a while so I needed to familiarize with how modules work :)

**Comment by ethantkoenig** [comment]
@lafriks: added a `v1.0.0` tag

**Pull request merged**
